# Generated by Django 3.2.7 on 2021-12-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_basket_basketitems_order_product_productimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image1',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='prod-placeholder.png', upload_to='products'),
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
