# Generated by Django 3.2.7 on 2021-12-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20211214_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_instructions',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image2',
            field=models.ImageField(blank=True, default='prod-placeholder.png', upload_to='products'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image3',
            field=models.ImageField(blank=True, default='prod-placeholder.png', upload_to='products'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image4',
            field=models.ImageField(blank=True, default='prod-placeholder.png', upload_to='products'),
        ),
    ]
